const bruxos = [
    {
        id: 1,
        nome: "Harry Potter",
        casa: "Grifinória",
        ano: 7,
        varinha: "Azevinho e pena de fênix, 28cm",
        mascote: "Coruja (Edwiges)",
        patrono: "Cervo",
        especialidade: "Sobreviver a Voldemort 😎",
    },
    {
        id: 2,
        nome: "Hermione Granger",
        casa: "Grifinória",
        ano: 7,
        varinha: "Videira e fibra de coração de dragão, 27cm",
        mascote: "Gato (Bichento)",
        patrono: "Lontra",
        especialidade: "Saber tudo de tudo",
    },
    {
        id: 3,
        nome: "Ron Weasley",
        casa: "Grifinória",
        ano: 7,
        varinha: "Salgueiro e crina de unicórnio, 35cm",
        mascote: "Rato (Perebas)",
        patrono: "Terrier Jack Russell",
        especialidade: "Xadrez Bruxo",
    },
    {
        id: 4,
        nome: "Draco Malfoy",
        casa: "Sonserina",
        ano: 7,
        varinha: "Espinheiro e crina de unicórnio, 25cm",
        mascote: "Coruja (não nomeada)",
        patrono: "Desconhecido",
        especialidade: "Ser irritante",
    },
    {
        id: 5,
        nome: "Luna Lovegood",
        casa: "Corvinal",
        ano: 6,
        varinha: "Madeira de cerejeira e núcleo desconhecido",
        mascote: "Nenhum",
        patrono: "Lebre",
        especialidade: "Ver criaturas imaginárias (ou não) 👻",
    },
    {
        id: 6,
        nome: "Neville Longbottom",
        casa: "Grifinória",
        ano: 7,
        varinha: "Macieira e crina de unicórnio, 36cm",
        mascote: "Sapo (Trevor)",
        patrono: "Lontra",
        especialidade: "Herbologia 🌿",
    },
    {
        id: 7,
        nome: "Severus Snape",
        casa: "Sonserina",
        ano: "N/A",
        varinha: "Nogueira e pena de fênix, 25cm",
        mascote: "Nenhum",
        patrono: "Cervo",
        especialidade: "Poções e Defesa Contra as Artes das Trevas",
    },
    {
        id: 8,
        nome: "Alvo Dumbledore",
        casa: "Grifinória",
        ano: "N/A",
        varinha: "Sabugueiro e pena de fênix, 38cm",
        mascote: "Fênix (Fawkes)",
        patrono: "Desconhecido",
        especialidade: "Ser o bruxo mais poderoso de todos os tempos ✨",
    },
    {
        id: 9,
        nome: "Sirius Black",
        casa: "Grifinória",
        ano: "N/A",
        varinha: "Nogueira e crina de unicórnio, 36cm",
        mascote: "Cão (Lufa-Lufa)",
        patrono: "Cão",
        especialidade: "Animago (cão grande preto) 🐺",
    },
    {
        id: 10,
        nome: "Rubeus Hagrid",
        casa: "Grifinória",
        ano: "N/A",
        varinha: "Cipreste e coração de dragão, 50cm (quebrada)",
        mascote: "Cachorro (Fang) e Hipogrifo (Bicuço)",
        patrono: "Nenhum",
        especialidade: "Cuidar de criaturas mágicas 🐉",
    },
    {
        id: 11,
        nome: "Minerva McGonagall",
        casa: "Grifinória",
        ano: "N/A",
        varinha: "Cipreste e núcleo desconhecido, 23cm",
        mascote: "Gato (não nomeado)",
        patrono: "Gato",
    },
    {
        id: 12,
        nome: "Bellatrix Lestrange",
        casa: "Sonserina",
        ano: "N/A",
        varinha: "Nogueira e núcleo desconhecido, 30cm",
        mascote: "Nenhum",
        patrono: "Desconhecido",
        especialidade: "Torturar pessoas 😈",
    },
    {
        id: 13,
        nome: "Ginny Weasley",
        casa: "Grifinória",
        ano: 7,
        varinha: "Salgueiro e núcleo desconhecido, 31cm",
        mascote: "Coruja (Errol)",
        patrono: "Cervo",
        especialidade: "Quadribol 🏆",
    },
    {
        id: 14,
        nome: "Fred Weasley",
        casa: "Grifinória",
        ano: 7,
        varinha: "Salgueiro e núcleo desconhecido, 32cm",
        mascote: "Coruja (Errol)",
        patrono: "Cervo",
        especialidade: "Piadas e travessuras 😂",
    },
    {
        id: 15,
        nome: "George Weasley",
        casa: "Grifinória",
        ano: 7,
        varinha: "Salgueiro e núcleo desconhecido, 32cm",
        mascote: "Coruja (Errol)",
        patrono: "Cervo",
        especialidade: "Piadas e travessuras 😂",
    },
    {
        id: 16,
        nome: "Alastor Moody",
        casa: "Grifinória",
        ano: "N/A",
        varinha: "Nogueira e núcleo desconhecido, 30cm",
        mascote: "Nenhum",
        patrono: "Desconhecido",
        especialidade: "Auror e caçar com com a perna de madeira 🦵",
    },
    {
        id: 17,
        nome: "Dolores Umbridge",
        casa: "Sonserina",
        ano: "N/A",
        varinha: "Cipreste e núcleo desconhecido, 25cm",
        mascote: "Nenhum",
        patrono: "Desconhecido",
        especialidade: "Torturar alunos 😡",
    }
]; 

export default { bruxos };